name: first workflow
on: workflow_dispatch
jobs:
 first-job:
  runs-on: ubuntu-22.04
  steps:
   - name: print github context
     run: echo "${{ toJSON(github) }}"
   - name: print bye
     run: echo bye
   
